#!/bin/sh
# Import shapefile data for Bristol
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/parks-and-green-spaces --copy-all-fields --input=data/bristol/env_data/parks-and-greens-spaces.shp "--add-tags=#source=cdtweek-2023,#layer=parks_and_green_spaces" --output=bristol_parks_and_green_spaces.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/access-points --copy-all-fields --input=data/bristol/env_data/access_points.shp "--add-tags=#source=cdtweek-2023,#layer=access_points" --output=bristol_access_points.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/conservation-areas --copy-all-fields --input=data/bristol/env_data/conservation-areas.shp "--add-tags=#source=cdtweek-2023,#layer=conservation_areas" --output=bristol_conservation_areas.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/trees --copy-all-fields --input=data/bristol/env_data/trees.shp "--add-tags=#source=cdtweek-2023,#layer=trees" --output=bristol_trees.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/mental-health --copy-all-fields --input=data/bristol/hlth_data/Bristol_mental_health_refactored.shp "--add-tags=#source=cdtweek-2023,#layer=mental_health" --output=bristol_mental_health.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/active-travel --copy-all-fields --input=data/bristol/hlth_data/getting-bristol-moving-active-travel-map-suggestions.shp "--add-tags=#source=cdtweek-2023,#layer=active_travel" --output=bristol_active_travel.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/air-quality --copy-all-fields --input=data/bristol/hlth_data/air-quality-management-areas.shp "--add-tags=#source=cdtweek-2023,#layer=air_quality" --output=bristol_air_quality.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/food-insecurity --copy-all-fields --input=data/bristol/nutr_data/Bristol_food_insecurity_refactored.shp "--add-tags=#source=cdtweek-2023,#layer=food_insecurity" --output=bristol_food_insecurity.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/food-banks --copy-all-fields --input=data/bristol/nutr_data/food_banks.shp "--add-tags=#source=cdtweek-2023,#layer=food_banks" --output=bristol_food_banks.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/nutrition --copy-all-fields --input=data/bristol/nutr_data/Bristol_nutrition_LSOA_refactored.shp "--add-tags=#source=cdtweek-2023,#layer=nutrition" --output=bristol_nutrition.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/food-spend --copy-all-fields --input=data/bristol/nutr_data/Bristol_food_spend_LSOA_refactored.shp "--add-tags=#source=cdtweek-2023,#layer=food_spend" --output=bristol_food_spend.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/public-toilets --copy-all-fields --input=data/bristol/amenities_data/amenities_public_toilets.shp "--add-tags=#source=cdtweek-2023,#layer=public_toilets" --output=bristol_public_toilets.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/pt-stops --copy-all-fields --input=data/bristol/amenities_data/amenities_PT_stops.shp "--add-tags=#source=cdtweek-2023,#layer=pt_stops" --output=bristol_pt_stops.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/leisure-spaces --copy-all-fields --input=data/bristol/amenities_data/amenities_leisure_spaces.shp "--add-tags=#source=cdtweek-2023,#layer=leisure_spaces" --output=bristol_leisure_spaces.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/green-blue-space --copy-all-fields --input=data/bristol/amenities_data/amenities_green_blue_space.shp "--add-tags=#source=cdtweek-2023,#layer=green_blue_space" --output=bristol_green_blue_space.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/green-blue-space-ALL --copy-all-fields --input=data/bristol/amenities_data/amenities_green_blue_space_ALL.shp "--add-tags=#source=cdtweek-2023,#layer=green_blue_space_ALL" --output=bristol_green_blue_space_ALL.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/cultural-space --copy-all-fields --input=data/bristol/amenities_data/amenities_cultural_space.shp "--add-tags=#source=cdtweek-2023,#layer=cultural_space" --output=bristol_cultural_space.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/benches --copy-all-fields --input=data/bristol/amenities_data/amenities_benches.shp "--add-tags=#source=cdtweek-2023,#layer=benches" --output=bristol_benches.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/amenities-all --copy-all-fields --input=data/bristol/amenities_data/amenities_ALL.shp "--add-tags=#source=cdtweek-2023,#layer=amenities_all" --output=bristol_amenities_all.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/amenities=financial --copy-all-fields --input=data/bristol/amenities_data/amenities_financial.shp "--add-tags=#source=cdtweek-2023,#layer=amenities_financial" --output=bristol_amenities_financial.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/food-spaces --copy-all-fields --input=data/bristol/amenities_data/amenities_food_spaces.shp "--add-tags=#source=cdtweek-2023,#layer=food_spaces" --output=bristol_food_spaces.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/community-service --copy-all-fields --input=data/bristol/amenities_data/amenities_community_service.shp "--add-tags=#source=cdtweek-2023,#layer=community_service" --output=bristol_community_service.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/health --copy-all-fields --input=data/bristol/amenities_data/amenities_health.shp "--add-tags=#source=cdtweek-2023,#layer=health" --output=bristol_health.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/food --copy-all-fields --input=data/bristol/amenities_data/amenities_food.shp "--add-tags=#source=cdtweek-2023,#layer=food" --output=bristol_food.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/population_65plus --copy-all-fields --input=data/bristol/pop_data/lsoa_population_65plus.shp "--add-tags=#source=cdtweek-2023,#layer=population_65plus" --output=bristol_population_65plus.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/aipc-geo --copy-all-fields --input=data/bristol/pop_data/aipc_geo.shp "--add-tags=#source=cdtweek-2023,#layer=aipc_geo" --output=bristol_aipc_geo.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/public-toilets --copy-all-fields --input=data/bristol/poi_data/public-toilets-community.shp "--add-tags=#source=cdtweek-2023,#layer=public_toilets" --output=bristol_public_toilets.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/libraries --copy-all-fields --input=data/bristol/poi_data/libraries.shp "--add-tags=#source=cdtweek-2023,#layer=libraries" --output=bristol_libraries.index
b6-ingest-gdal --namespace=diagonal.works/cdtweek-2023/bristol/imd-lsoa --copy-all-fields --input=data/bristol/ecnm_data/Bristol_imd_LSOA.shp "--add-tags=#source=cdtweek-2023,#layer=imd_lsoa" --output=bristol_imd_lsoa.index
# Use a side-effect of the b6-connect tool, which connects points to the highway
# network, to merge the separate indices above into a single file. It doesn't
# actually connect anything, as we don't read a street network here
b6-connect --input=`ls -1 bristol_*.index | paste -sd, -` --output=merged_bristol.index